/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package navescombate.UI;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JButton;
import javax.swing.JPanel;
import navescombate.UI.Animation.Animacion;

/**
 *
 * @author atenea
 */
public class CampoBatalla extends javax.swing.JFrame {

    /**
     * Creates new form CampoBatalla
     */
    Animacion animation;
    int posX;
    int posY;
    CampoBatalla campo = this;

    public CampoBatalla() {
        initComponents();
        this.panel.addMouseListener(new MouseAdapter() {

            @Override
            public void mousePressed(MouseEvent me) {
                if (animation == null) {
                 load();
                }
                if (animation.iniciada) {
                    animation.Disparar();
                } else {

                    animation.init();
                }
            }

        });
        this.panel.addMouseMotionListener(new MouseAdapter() {

            @Override
            public void mouseMoved(MouseEvent e) {
                if (animation!=null&&animation.iniciada) {
                    posX = e.getX();
                    posY = e.getY();
//                animation.MoveMousePoint(posX, posY);

                    animation.MoveMouseX(posX);
                    panel.updateUI();
                }
            }

            @Override
            public void mousePressed(MouseEvent me) {
                animation.Disparar();
            }

        });

    }
    
    public void load(){
        animation = new Animacion(campo);
        this.panel.setFocusable(true);
        this.panel.add(animation);
        
    }

    public JPanel getPanel() {
        return this.panel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 300));

        panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panel.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        panel.setMinimumSize(new java.awt.Dimension(4, 4));
        panel.setPreferredSize(new java.awt.Dimension(4, 4));
        panel.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables

}
